{
    "layout":{
    "css":"gantt_container",
        "rows":[
        {
            "cols":[
                {
                    "view":"grid",
                    "scrollX":"scrollHor",
                    "scrollY":"scrollVer"
                },
                {
                    "resizer":true,
                    "width":1
                },
                {
                    "view":"timeline",
                    "scrollX":"scrollHor",
                    "scrollY":"scrollVer"
                },
                {
                    "view":"scrollbar",
                    "id":"scrollVer"
                }
            ]
        },
        {
            "view":"scrollbar",
            "id":"scrollHor",
            "height":20
        }
    ],
        "id":"main"
},
    "links":{
    "finish_to_start":"0",
        "start_to_start":"1",
        "finish_to_finish":"2",
        "start_to_finish":"3"
},
    "types":{
    "task":"task",
        "project":"project",
        "milestone":"milestone",
        "placeholder":"placeholder"
},
    "auto_types":false,
    "duration_unit":"day",
    "work_time":false,
    "correct_work_time":false,
    "skip_off_time":false,
    "cascade_delete":true,
    "autosize":false,
    "autosize_min_width":0,
    "autoscroll":true,
    "autoscroll_speed":30,
    "show_links":true,
    "show_task_cells":true,
    "static_background":false,
    "branch_loading":false,
    "branch_loading_property":"$has_child",
    "show_loading":false,
    "show_chart":true,
    "show_grid":true,
    "min_duration":3600000,
    "xml_date":"%d-%m-%Y %H:%i",
    "api_date":"%d-%m-%Y %H:%i",
    "start_on_monday":true,
    "server_utc":false,
    "show_progress":true,
    "fit_tasks":false,
    "select_task":true,
    "scroll_on_click":true,
    "preserve_scroll":true,
    "readonly":false,
    "date_grid":"%Y-%m-%d",
    "drag_links":true,
    "drag_progress":true,
    "drag_resize":true,
    "drag_project":false,
    "drag_move":true,
    "drag_mode":{
    "resize":"resize",
        "progress":"progress",
        "move":"move",
        "ignore":"ignore"
},
    "round_dnd_dates":true,
    "link_wrapper_width":20,
    "root_id":0,
    "autofit":false,
    "columns":[
    {
        "name":"text",
        "tree":true,
        "width":156,
        "resize":true
    },
    {
        "name":"start_date",
        "align":"center",
        "resize":true,
        "width":90
    },
    {
        "name":"duration",
        "align":"center",
        "width":70
    },
    {
        "name":"add",
        "width":44,
        "min_width":44,
        "max_width":44
    }
],
    "step":1,
    "scale_unit":"year",
    "scale_offset_minimal":true,
    "subscales":[
    {
        "unit":"month",
        "step":1,
        "date":"%F",
        "index":1
    }
],
    "inherit_scale_class":false,
    "time_step":60,
    "duration_step":1,
    "date_scale":"%Y",
    "task_date":"%d %F %Y",
    "time_picker":"%H:%i",
    "task_attribute":"task_id",
    "link_attribute":"link_id",
    "layer_attribute":"data-layer",
    "buttons_left":[
    "gantt_save_btn",
    "gantt_cancel_btn"
],
    "_migrate_buttons":{
    "dhx_save_btn":"gantt_save_btn",
        "dhx_cancel_btn":"gantt_cancel_btn",
        "dhx_delete_btn":"gantt_delete_btn"
},
    "buttons_right":[
    "gantt_delete_btn"
],
    "lightbox":{
    "sections":[
        {
            "name":"description",
            "height":38,
            "map_to":"text",
            "type":"textarea",
            "focus":true
        },
        {
            "name":"details",
            "height":38,
            "map_to":"text",
            "type":"textarea"
        },
        {
            "name":"priority",
            "height":22,
            "map_to":"priority",
            "type":"select",
            "options":[
                {
                    "key":1,
                    "label":"High"
                },
                {
                    "key":2,
                    "label":"Normal"
                },
                {
                    "key":3,
                    "label":"Low"
                }
            ]
        },
        {
            "name":"time2",
            "height":72,
            "map_to":"auto",
            "type":"duration",
            "time_format":[
                "%d",
                "%m",
                "%Y",
                "%H:%i"
            ]
        },
        {
            "name":"time",
            "height":72,
            "map_to":"auto",
            "type":"duration"
        }
    ],
        "project_sections":[
        {
            "name":"description",
            "height":70,
            "map_to":"text",
            "type":"textarea",
            "focus":true
        },
        {
            "name":"type",
            "type":"typeselect",
            "map_to":"type"
        },
        {
            "name":"time",
            "type":"duration",
            "readonly":true,
            "map_to":"auto"
        }
    ],
        "milestone_sections":[
        {
            "name":"description",
            "height":70,
            "map_to":"text",
            "type":"textarea",
            "focus":true
        },
        {
            "name":"type",
            "type":"typeselect",
            "map_to":"type"
        },
        {
            "name":"time",
            "type":"duration",
            "single_date":true,
            "map_to":"auto"
        }
    ]
},
    "drag_lightbox":true,
    "sort":false,
    "details_on_create":true,
    "details_on_dblclick":true,
    "initial_scroll":true,
    "task_scroll_offset":100,
    "order_branch":"marker",
    "order_branch_free":false,
    "task_height":10,
    "min_column_width":60,
    "min_grid_column_width":70,
    "grid_resizer_column_attribute":"column_index",
    "grid_resizer_attribute":"grid_resizer",
    "keep_grid_width":false,
    "grid_resize":false,
    "show_unscheduled":true,
    "readonly_property":"readonly",
    "editable_property":"editable",
    "calendar_property":"calendar_id",
    "resource_calendars":{

},
    "type_renderers":{

},
    "open_tree_initially":false,
    "optimize_render":true,
    "prevent_default_scroll":false,
    "show_errors":true,
    "wai_aria_attributes":true,
    "smart_scales":true,
    "rtl":false,
    "placeholder_task":false,
    "editor_types":{
    "text":{

    },
    "number":{

    },
    "select":{

    },
    "date":{

    },
    "predecessor":{

    }
},
    "resource_property":"owner_id",
    "resource_store":"resource",
    "resource_render_empty_cells":false,
    "touch_drag":500,
    "touch":false,
    "touch_feedback":true,
    "touch_feedback_duration":1,
    "multiselect":true,
    "multiselect_one_level":false,
    "scale_height":50,
    "scroll_size":17,
    "grid_width":360,
    "row_height":35,
    "link_line_width":2,
    "link_arrow_size":6,
    "lightbox_additional_height":75
}